### ISSUE TITLE
yaml parameters in preamble.tex

### ISSUE THREAD

**Issue by carlosyanez** [cynkra/indiedown#13]
Hi,
in the first place, thanks for creating this package!

I'm trying to add headers and footers to my template, for which I'm adding the below code into preamble.tex:

```
%fancy headers
\usepackage{fancyhdr}

\pagestyle{fancy}
\fancyhead[L]{$title$}
\fancyhead[R]{ }
\fancyfoot[L]{ }
\fancyfoot[C]{ }
\fancyfoot[R]{\thepage}
```

In this part of the document, I would like to add the title and author, for which I would like to use YAML parameters from the Rmd file. According to what I've found [here](https://tex.stackexchange.com/questions/319364/cant-make-fancyhdr-work-with-pandoc-yaml-header), this can be accomplished by passing the YAML parameters within $$ in LaTeX (e.g. $title$). However, when I add the code into preamble.tex, I get literally _title_ printed on the pdf file (instead of the value of the title parameter).

Is there anything I am missing to configure to get the right result?
Thanks,
Carlos

**Comment by krlmlr** [comment]
Thanks! Could you please share a reproducible example?

**Comment by carlosyanez** [comment]
No worries, here it's what have down:

1. Created new indiedown package skeleton with `devtools::install("mydown")`.
2. Edited inst/indiedown/preamble.tex and added (at the end of the file):

`
\usepackage{fancyhdr}
![Screen Shot 2021-06-07 at 8 42 42 am](https://user-images.githubusercontent.com/22521/120971061-82d00b80-c76c-11eb-9ebb-4669104514bc.png)

\pagestyle{fancy}
\fancyhead[L]{$title$}
\fancyhead[R]{Hello Workd}
\fancyfoot[L]{}
\fancyfoot[C]{\thepage}
\fancyfoot[R]{}
`

3. Installed package with `devtools::install("mydown") `and re-started RStudio.
4. Created a new document using the template.
5. Knitted document, out shown below:

![Screen Shot 2021-06-07 at 8 42 42 am](https://user-images.githubusercontent.com/22521/120971123-93808180-c76c-11eb-8bbf-fb9a24326c6f.png)

I'm running R 4.1.0.

I'm not versed in pancod, but after reading about this on the Internet, this maybe due to lacking the right markdown extension ( [yaml_metadata_block](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block) ?), which doesn't seem to be called during knitting. (I could be wrong though)

![Screen Shot 2021-06-07 at 8 49 36 am](https://user-images.githubusercontent.com/22521/120972563-266deb80-c76e-11eb-8fdb-9465ae6c9982.png)

Thanks for your help.!

**Comment by angelicambg** [comment]
@carlosyanez this can be solved in two ways. And I would suggest using the first one in case you want to customize more the headers and footers.

1. Add to the preamble the package `\usepackage{fancyhdr} \pagestyle{fancy}` and then create a function similar to [this](https://cynkra.github.io/indiedown/articles/walkthrough.html#a-customized-title-page-) in the R folder of your package. So in your case, it will look like this:

```
cd_footer <- function(head_title = "my title") {
  indiedown_glue(
    r"(
    \fancyhead[L]{<<head_title>>} 
    \fancyhead[R]{Hello Workd} 
    \fancyfoot[L]{} 
    \fancyfoot[C]{\thepage}
    \fancyfoot[R]{}
    )"
  )
}
```

Then build the package again and call this function with an R chunk in your Rmd. If you want to customize more the headers and footers, you can include more parameters in the function.

```
```{r}
cd_footer(head_title = "new title")

```

2. The second option is changing the preamble as you did, but using  ` \fancyhead[L]{\mytitle} `, and redefining the command to pass the title. To redefine the command, use in the header of your Rmd:

```
header-includes:
  - \newcommand{\mytitle}{new title}
```
I wouldn't recommend this option because if you want to add more parameters you need to define them all in the header.

**Comment by carlosyanez** [comment]
Thanks!. I followed approach 1 and it is all working now.
