### ISSUE TITLE
remove tidyverse call from template

### ISSUE THREAD

**Issue by mbannert** [cynkra/indiedown#24]
Currently, {indiedown} does not depend on {tidyverse} in the technical sense that it imports, depends or suggests {tidyverse}, but the [standard template](https://github.com/cynkra/indiedown/blob/5d244bc257c4fc1a3547a62b635836ab3b5df28f/inst/mypackage/inst/rmarkdown/templates/report/skeleton/skeleton.Rmd#L17) calls `library(tidyverse)`. 

I suggest to remove this from the template since many people who even use the tidyverse packages are only using specific package like {dplyr}, {purrr} or {ggplot2}. 

Let me know in case I may create a PR for this.

**Comment by christophsax** [comment]
Yes, makes sense to remove. Thanks!
