### ISSUE TITLE
Suggest to use `remotes` instead of `devtools` when installing from GH

### ISSUE THREAD

**Issue by pat-s** [cynkra/indiedown#7]
In the README

```
devtools::install_github("cynkra/indiedown") -> remotes::install_github("cynkra/indiedown")
```

**Comment by krlmlr** [comment]
We need devtools further below.

**Comment by pat-s** [comment]
Fair enough. I still see many `devtools::install_github()` recs in READMEs and I believe `remotes::` should be used as a best practice.
